import 'package:firebase/auth_page.dart';
import 'package:firebase/main_page.dart';



import 'package:flutter/material.dart'; // Needed for WidgetsFlutterBinding
import 'package:firebase_core/firebase_core.dart'; // Needed for Firebase.initializeApp()
import 'firebase_options.dart'; // Auto-generated by flutterfire configure



void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Makes sure Flutter is ready
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Connects to Firebase
  );

  runApp(const MyApp()); // Start your app after Firebase is ready
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MainPage(),
    );
  }
}
